"""This file is generated automatically. Do not manually modify it."""
class GeneratedConfig:
   config___ChromelessWindow = False
   config___DEBUG = True
   config___capture_mode = 'fast'
   config___check_import = False
   config___cloud_genshin = False
   config___corr_degree = 0.95
   config___determining_strict_weight = 0.9
   config___device_paddle = 'cpu'
   config___device_torch = 'auto'
   config___interaction_mode = 'Desktop'
   config___lang = '$locale$'
   config___mission_group = 'AutoCollectorMission.json'
   config___python32_path = ''
   config___using_alpha_channel = True
   config___version = 'v0.7.2.779'
   auto_collector___collect_mode = 'Auto'
   auto_collector___collection_area = 'ALL'
   auto_collector___collection_name = '史莱姆 - 蒙德'
   auto_collector___collection_type = 'ENEMY'
   auto_collector___minimum_times_mask_col_id = 10000
   auto_aim___auto_distance = True
   auto_aim___auto_move = False
   auto_aim___fps = 20
   auto_aim___max_number_of_enemy_loops = 150
   auto_aim___reset_time = 40
   auto_combat___teamfile = 'team.json'
   auto_domain___domain_name = '山脊守望'
   auto_domain___domain_stage_name = '不移II'
   auto_domain___domain_times = 1
   auto_domain___domain_type_name = '不移II'
   auto_domain___fast_mode = True
   auto_domain___isLiYueDomain = False
   auto_domain___resin = '20'
   auto_pickup___blacklist = []
   auto_pickup___blacklist = []
