CONFIGNAME_GENERAL = "General"
CONFIGNAME_COLLECTOR = "Collector"
CONFIGNAME_COMBAT = "Combat"
CONFIGNAME_DOMAIN = "Domain"
CONFIGNAME_KEYMAP = "Keymap"
CONFIG_FILE_NAMES = [CONFIGNAME_GENERAL, CONFIGNAME_COLLECTOR, CONFIGNAME_COMBAT,
                         CONFIGNAME_DOMAIN, CONFIGNAME_KEYMAP]