CONFIGNAME_CONFIG = "config"
CONFIGNAME_AIM = "auto_aim"
CONFIGNAME_COLLECTOR = "auto_collector"
CONFIGNAME_COMBAT = "auto_combat"
CONFIGNAME_DOMAIN = "auto_domain"
CONFIGNAME_PICKUP = "auto_pickup"
CONFIGNAME_KEYMAP = "keymap"
CONFIG_FILE_NAMES = [CONFIGNAME_CONFIG, CONFIGNAME_COLLECTOR, CONFIGNAME_AIM, CONFIGNAME_COMBAT,
                         CONFIGNAME_DOMAIN, CONFIGNAME_PICKUP, CONFIGNAME_PICKUP]

