from source.util import *

AHEAD = 'W'
LEFT = "A"
BACK = "S"
RIGHT = "D"

CORRECT_DEGREE = GIAconfig.General_CorrDegree
HORIZONTAL = 1
VERTICALLY = 2
VERTICALLY_AND_HORIZONTAL = 3

CLIMBING = "CLIMBING"
SWIMMING = "SWIMMING"
WALKING = "WALKING"
FLYING = "FLYING"