from source.util import *

AHEAD = 0
LEFT = 1
RIGHT = 2
BACK = 3
CORRECT_DEGREE = GIAconfig.General_CorrDegree
HORIZONTAL = 1
VERTICALLY = 2
VERTICALLY_AND_HORIZONTAL = 3

CLIMBING = "CLIMBING"
SWIMMING = "SWIMMING"
WALKING = "WALKING"
FLYING = "FLYING"