from source.util import *

MOVE_AHEAD = 'W'
MOVE_LEFT = "A"
MOVE_BACK = "S"
MOVE_RIGHT = "D"
MOVE_START = 'down'
MOVE_END = 'up'

CORRECT_DEGREE = GIAconfig.General_CorrDegree
HORIZONTAL = 1
VERTICALLY = 2
VERTICALLY_AND_HORIZONTAL = 3

CLIMBING = "CLIMBING"
SWIMMING = "SWIMMING"
WALKING = "WALKING"
FLYING = "FLYING"