import gettext, sys
sys.argv.pop(0)
LANG = sys.argv[0]
l10n = gettext.translation(LANG, localedir = r"../doc/markdown_i18n/locale", languages=[LANG])
l10n.install()
_ = l10n.gettext
f = open(r"../doc\en_US\code_standard\abandoned/add_priority_waypoints.md", "w", encoding="utf-8")
f.write(_("# add_pripority_waypoints")+str('\n'))
f.write("\n")
f.write(_("1.打开add_pripority_waypoints.py文件")+str('\n'))
f.write("\n")
f.write(_("2.运行add_mode函数")+str('\n'))
f.write("\n")
f.write(_("3.在原神游戏内行走，程序自动标点，结束后关闭程序")+str('\n'))
f.write("\n")
f.write(_("4.注释掉add_mode函数，运行edit_mode函数，注意提示")+str('\n'))
f.write("\n")
f.write(_("5.在出现的窗口中，观察并记下错误的点")+str('\n'))
f.write("\n")
f.write(_("6.关闭窗口，在控制台输入错误点的编号以删除，可以输入多个，用逗号分隔。")+str('\n'))
f.write("\n")
f.write(_("7.循环过程5-6")+str('\n'))
f.write("\n")
f.write(_("8.输入0，按回车退出")+str('\n'))
f.write("\n")
f.write(_("## 注意")+str('\n'))
f.write("\n")
f.write(_("1.地图大小比例标准为：先放到最小，然后按两次放大地图按钮")+str('\n'))
f.write("\n")
f.write(_("2.尽量选择坡度较缓的地方标点，绕开直接攀岩，特别是不可通过的地形要尽量绕开。")+str('\n'))
f.write("\n")
f.write(_("3.在大地图中，离当前坐标越远的地方准确度越低，因此应在需要修改的地方附近启动edit_mode\n")+str('\n'))
f.write("\n")
f.close()