CONTAIN_MATCHING = 0
ACCURATE_MATCHING = 1
TWICE_AND_MATCHING = 3
TWICE_OR_MATCHING = 5
TWICE_FRONTANDBACK_MATCHING = 4
TWICE_FRONTANDBACK_SEQUENTIAL_MATCHING = 6
REPEATLY_MATCHING = 7
SHAPE_MATCHING = 8

CHANNEL_RED = 2
RETURN_TEXT = 1
RETURN_POSITION = 0
RETURN_POINT = 3