"""Constant vars."""

DESKTOP_CN = "Desktop_CN"
DESKTOP_EN = "Desktop_EN"
MOBILE_CN = "Mobile_CN"
MOBILE_EN = "Mobile_EN"
DEVICE = DESKTOP_CN
INTERACTION_DESKTOP = "Desktop"
INTERACTION_EMULATOR = "Emulator"
INTERACTION_DESKTOP_BACKGROUND = "DesktopBackground"
INTERACTION_MODE = INTERACTION_DESKTOP # Normal, Adb, Dm
BBG = 100001
ANGLE_NORMAL = 0
ANGLE_NEGATIVE_Y = 1
ANGLE_NEGATIVE_X = 2
ANGLE_NEGATIVE_XY = 3
PROCESS_NAME = ["YuanShen.exe", "GenshinImpact.exe"]
SCREEN_CENTER_X = 1920/2
SCREEN_CENTER_Y = 1080/2
GIA_VERSION = "v0.8.3.934"